<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<LangVersion>10.0</LangVersion>
		<Nullable>disable</Nullable>
		<IsPackable>false</IsPackable>
		<IsTestProject>false</IsTestProject>
		<RootNamespace>SoapClientCallAssistTests.Common</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\SoapClientCallAssist\SoapClientCallAssist.csproj" />
	</ItemGroup>

</Project>
