
#nullable disable

using Microsoft.VisualStudio.TestTools.UnitTesting;
using SoapClientCallAssist.Abstractions;
using SoapClientCallAssist.Mapping;
using SoapClientCallAssistTests.Soap12.Helpers.Mapper;
using SoapClientCallAssistTests.Soap12.Models;
using System.Linq;
using System.Xml.Linq;

namespace SoapClientCallAssistTests.Soap12.Tests.Mapper.Bind;

[TestClass]
public sealed class MapperBindEnvelopeShapeTests
{
    private const string Payload = "<Id>42</Id><Name>widget</Name>";

    private readonly ISoapModelMapper _mapper = new SoapModelMapper();

    [DataTestMethod]
    [DataRow("soap", DisplayName = "soap: prefixed envelope")]
    [DataRow("s", DisplayName = "s: prefixed envelope (WCF style)")]
    [DataRow("env", DisplayName = "env: prefixed envelope")]
    [DataRow("SOAP-ENV", DisplayName = "SOAP-ENV: prefixed envelope")]
    public void FromResponse_AnyEnvelopePrefix_BindsIdentically_Test(string prefix)
    {
        var response = MapperBindEnvelope.Wrap12(MapperBindEnvelope.Payload("Flat", Payload), prefix);

        Assert.IsTrue(response.Contains($"<{prefix}:Body>"), prefix);

        var result = _mapper.FromResponse<MapperBindFlat>(response, MapperBindEnvelope.Protocol12);

        MapperBindAssert.Succeeded(result);
        Assert.AreEqual(42, result.Response.Id);
        Assert.AreEqual("widget", result.Response.Name);
    }

    [TestMethod]
    public void FromResponse_EnvelopeNamespaceOnTheDefaultNamespace_BindsWithNoPrefixAtAll_Test()
    {
        var response = MapperBindEnvelope.Wrap12(MapperBindEnvelope.Payload("Flat", Payload), null);

        Assert.IsTrue(response.Contains($"<Envelope xmlns=\"{MapperBindEnvelope.Soap12Ns}\">"));

        var result = _mapper.FromResponse<MapperBindFlat>(response, MapperBindEnvelope.Protocol12);

        MapperBindAssert.Succeeded(result);
        Assert.AreEqual(42, result.Response.Id);
    }

    [TestMethod]
    public void FromResponse_Soap11EnvelopeWhileTheCallerPassesTheSoap12Namespace_StillLocatesTheBody_Test()
    {
        var response = MapperBindEnvelope.Wrap11(MapperBindEnvelope.Payload("Flat", Payload), "s");

        var result = _mapper.FromResponse<MapperBindFlat>(response, MapperBindEnvelope.Protocol12);

        MapperBindAssert.Succeeded(result);
        Assert.AreEqual(42, result.Response.Id);
    }

    [TestMethod]
    public void FromResponse_IndentedEnvelopeWithAComment_BindsFromTheFirstElementChild_Test()
    {
        var response =
            $"<soap:Envelope xmlns:soap=\"{MapperBindEnvelope.Soap12Ns}\">\r\n"
            + "  <soap:Body>\r\n"
            + "    <!-- generated by the service -->\r\n"
            + $"    <Flat xmlns=\"{MapperBindNs.Contract}\">\r\n"
            + "      <Id>42</Id>\r\n"
            + "      <Name>widget</Name>\r\n"
            + "    </Flat>\r\n"
            + "  </soap:Body>\r\n"
            + "</soap:Envelope>";

        Assert.IsTrue(response.Contains("<!--"));
        Assert.IsTrue(response.Contains(">\r\n  "));

        var result = _mapper.FromResponse<MapperBindFlat>(response, MapperBindEnvelope.Protocol12);

        MapperBindAssert.Succeeded(result);
        Assert.AreEqual(42, result.Response.Id);
        Assert.AreEqual("widget", result.Response.Name);
    }

    [TestMethod]
    public void FromResponse_XmlDeclarationAndProcessingInstruction_AreSkipped_Test()
    {
        var response =
            "<?xml version=\"1.0\" encoding=\"utf-8\"?>"
            + "<?some-processing-instruction value=\"1\"?>"
            + $"<soap:Envelope xmlns:soap=\"{MapperBindEnvelope.Soap12Ns}\"><soap:Body>"
            + MapperBindEnvelope.Payload("Flat", Payload)
            + "</soap:Body></soap:Envelope>";

        var result = _mapper.FromResponse<MapperBindFlat>(response, MapperBindEnvelope.Protocol12);

        MapperBindAssert.Succeeded(result);
        Assert.AreEqual(42, result.Response.Id);
    }

    [TestMethod]
    public void FromResponse_BodyTagOverrideCarriesAPrefix_MatchesOnTheLocalPart_Test()
    {
        var response = MapperBindEnvelope.Wrap12(MapperBindEnvelope.Payload("Flat", Payload), "env");

        var result = _mapper.FromResponse<MapperBindFlat>(response, MapperBindEnvelope.Protocol12, "s:Body");

        MapperBindAssert.Succeeded(result);
        Assert.AreEqual(42, result.Response.Id);
    }

    [TestMethod]
    public void FromResponse_BodyTagOverrideNamesAPayloadElement_ReportsNoSingleBody_Test()
    {
        var response = MapperBindEnvelope.Wrap12(MapperBindEnvelope.Payload("Flat", Payload));

        var payloadElement = XDocument
            .Parse(response)
            .Descendants(XName.Get("Flat", MapperBindNs.Contract))
            .Single();
        Assert.AreEqual("42", payloadElement.Element(XName.Get("Id", MapperBindNs.Contract))?.Value);

        var result = _mapper.FromResponse<MapperBindFlat>(response, MapperBindEnvelope.Protocol12, "Flat");

        MapperBindAssert.FailedWithCode(result, MapperBindAssert.NoSingleBodyCode);
    }

    [TestMethod]
    public void FromResponse_BodyTagOverrideMatchesNothing_ReportsNoSingleBody_Test()
    {
        var response = MapperBindEnvelope.Wrap12(MapperBindEnvelope.Payload("Flat", Payload));

        var result = _mapper.FromResponse<MapperBindFlat>(
            response, MapperBindEnvelope.Protocol12, "NoSuchElement");

        MapperBindAssert.FailedWithCode(result, MapperBindAssert.NoSingleBodyCode);
    }

    [TestMethod]
    public void FromResponse_EnvelopeCarriesTwoBodies_ReportsNoSingleBody_Test()
    {
        var response =
            $"<soap:Envelope xmlns:soap=\"{MapperBindEnvelope.Soap12Ns}\">"
            + $"<soap:Body>{MapperBindEnvelope.Payload("Flat", "<Id>1</Id>")}</soap:Body>"
            + $"<soap:Body>{MapperBindEnvelope.Payload("Flat", "<Id>2</Id>")}</soap:Body>"
            + "</soap:Envelope>";

        Assert.AreEqual(
            2,
            XDocument.Parse(response)
                .Descendants(XName.Get("Body", MapperBindEnvelope.Soap12Ns))
                .Count());

        var result = _mapper.FromResponse<MapperBindFlat>(response, MapperBindEnvelope.Protocol12);

        MapperBindAssert.FailedWithCode(result, MapperBindAssert.NoSingleBodyCode);
    }

    [TestMethod]
    public void FromResponse_EnvelopeWithNoBody_ReportsNoSingleBody_Test()
    {
        var response =
            $"<soap:Envelope xmlns:soap=\"{MapperBindEnvelope.Soap12Ns}\">"
            + $"<soap:Header /></soap:Envelope>";

        var result = _mapper.FromResponse<MapperBindFlat>(response, MapperBindEnvelope.Protocol12);

        MapperBindAssert.FailedWithCode(result, MapperBindAssert.NoSingleBodyCode);
    }

    [TestMethod]
    public void FromResponse_BodyElementInAnUnrelatedNamespace_IsNotTreatedAsASoapBody_Test()
    {
        var response =
            "<Envelope xmlns=\"urn:not-soap\"><Body>"
            + MapperBindEnvelope.Payload("Flat", Payload)
            + "</Body></Envelope>";

        var result = _mapper.FromResponse<MapperBindFlat>(response, MapperBindEnvelope.Protocol12);

        MapperBindAssert.FailedWithCode(result, MapperBindAssert.NoSingleBodyCode);
    }

    [TestMethod]
    public void FromResponse_BodyNestedInsideTheHeader_ReportsNoSingleBody_Test()
    {
        var response =
            $"<soap:Envelope xmlns:soap=\"{MapperBindEnvelope.Soap12Ns}\">"
            + $"<soap:Header><soap:Body>{MapperBindEnvelope.Payload("Flat", Payload)}</soap:Body></soap:Header>"
            + "</soap:Envelope>";

        Assert.AreEqual(1, XDocument.Parse(response).Descendants(XName.Get("Body", MapperBindEnvelope.Soap12Ns)).Count());

        var result = _mapper.FromResponse<MapperBindFlat>(response, MapperBindEnvelope.Protocol12);

        MapperBindAssert.FailedWithCode(result, MapperBindAssert.NoSingleBodyCode);
        Assert.IsNull(result.Response);
    }

    [TestMethod]
    public void FromResponse_BodyInTheOtherProtocolNamespace_ReportsNoSingleBody_Test()
    {
        var response =
            $"<s12:Envelope xmlns:s12=\"{MapperBindEnvelope.Soap12Ns}\" xmlns:s11=\"{MapperBindEnvelope.Soap11Ns}\">"
            + $"<s11:Body>{MapperBindEnvelope.Payload("Flat", Payload)}</s11:Body>"
            + "</s12:Envelope>";

        var result = _mapper.FromResponse<MapperBindFlat>(response, MapperBindEnvelope.Protocol12);

        MapperBindAssert.FailedWithCode(result, MapperBindAssert.NoSingleBodyCode);
    }

    [TestMethod]
    public void FromResponse_EnvelopeNestedUnderANonSoapDocumentElement_ReportsNoSingleBody_Test()
    {
        var response = "<Wrapper>" + MapperBindEnvelope.Wrap12(MapperBindEnvelope.Payload("Flat", Payload)) + "</Wrapper>";

        var result = _mapper.FromResponse<MapperBindFlat>(response, MapperBindEnvelope.Protocol12);

        MapperBindAssert.FailedWithCode(result, MapperBindAssert.NoSingleBodyCode);
    }

    [TestMethod]
    public void FromResponse_BodyChildBelongsToAnotherOperation_ReportsTheAnchorMismatch_Test()
    {
        var response = MapperBindEnvelope.Wrap12(MapperBindEnvelope.Payload("Other", Payload));

        var result = _mapper.FromResponse<MapperBindFlat>(response, MapperBindEnvelope.Protocol12);

        MapperBindAssert.FailedWithCode(result, MapperBindAssert.AnchorMismatchCode);
        Assert.IsNull(result.Response);
        MapperBindAssert.MessagesContain(result, "'Other'");
        MapperBindAssert.MessagesContain(result, "'Flat'");
    }

    [TestMethod]
    public void FromResponse_EmptyBody_ReportsNothingToBindFrom_Test()
    {
        var response = MapperBindEnvelope.Wrap12(string.Empty);

        var result = _mapper.FromResponse<MapperBindFlat>(response, MapperBindEnvelope.Protocol12);

        MapperBindAssert.FailedWithCode(result, MapperBindAssert.EmptyBodyCode);
    }

    [TestMethod]
    public void FromResponse_BodyHoldingOnlyWhitespaceAndAComment_ReportsNothingToBindFrom_Test()
    {
        var response =
            $"<soap:Envelope xmlns:soap=\"{MapperBindEnvelope.Soap12Ns}\">\r\n"
            + "  <soap:Body>\r\n    <!-- nothing here -->\r\n  </soap:Body>\r\n"
            + "</soap:Envelope>";

        var result = _mapper.FromResponse<MapperBindFlat>(response, MapperBindEnvelope.Protocol12);

        MapperBindAssert.FailedWithCode(result, MapperBindAssert.EmptyBodyCode);
    }

    [TestMethod]
    public void FromResponse_EmptyString_ReportsAResponseFailure_Test()
    {
        var result = _mapper.FromResponse<MapperBindFlat>(string.Empty, MapperBindEnvelope.Protocol12);

        MapperBindAssert.FailedWithCode(result, MapperBindAssert.ResponseCode);
    }

    [TestMethod]
    public void FromResponse_NullString_ReportsAResponseFailureRatherThanThrowing_Test()
    {
        var result = _mapper.FromResponse<MapperBindFlat>(null, MapperBindEnvelope.Protocol12);

        MapperBindAssert.FailedWithCode(result, MapperBindAssert.ResponseCode);
    }
}
